@startuml

entity Category

Category: uuid id
Category: String name
Category: String description
Category: boolean is_active
Category: date created_at

Category: create()
Category: update()
Category: activate()
Category: deasctivate()
Category: delete()

@enduml
